In [3]:
from sklearn import datasets

digits = datasets.load_digits()
# digits

In [4]:
# 특성 행렬 생성
features = digits.data

In [5]:
# 타겟 벡터 생성
target = digits.target
target

array([0, 1, 2, ..., 8, 9, 8])

In [6]:
features[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [11]:
# 선형 회귀에 많이 사용되는 make_regression
from sklearn.datasets import make_regression

In [12]:
features, target, coefficients = make_regression(n_samples = 100,
                                                n_features = 3,
                                                n_informative = 3,
                                                n_targets = 1,
                                                noise = 0.0,
                                                coef = True,
                                                random_state = 1)

# 특성 행렬, 타겟 벡터, 정답 계수를 생성.
print('Feature Matrix\n', features[:3])
print('Target Vector\n', target[:3])

Feature Matrix
 [[ 1.29322588 -0.61736206 -0.11044703]
 [-2.793085    0.36633201  1.93752881]
 [ 0.80186103 -0.18656977  0.0465673 ]]
Target Vector
 [-10.37865986  25.5124503   19.67705609]


In [13]:
# 분류에 많이 사용되는 make_regression
from sklearn.datasets import make_classification

In [14]:
# 군집에 많이 사용되는 make_blobs
from sklearn.datasets import make_blobs

In [16]:
# URL을 통해서 실제 데이터들을 가져오기
import pandas as pd

url = 'https://tinyurl.com/simulated_data'
dataframe = pd.read_csv(url)
dataframe.head(2)

HTTPError: HTTP Error 404: Not Found

In [17]:
import pandas as pd

dataframe = pd.DataFrame()

In [18]:
dataframe['Name'] = ['Jacky', 'Steven']
dataframe['Age'] = [38, 25]
dataframe['Drvier'] = [True, False]

In [19]:
dataframe

Name  Age  Drvier
0   Jacky   38    True
1  Steven   25   False

In [21]:
new_person = pd.Series(['Molly',40,True], index=['Name','Age','Driver'])
new_person

Name      Molly
Age          40
Driver     True
dtype: object

In [23]:
dataframe.append(new_person, ignore_index=True)

Name  Age  Drvier  Driver
0   Jacky   38     1.0     NaN
1  Steven   25     0.0     NaN
2   Molly   40     NaN     1.0

In [24]:
dataframe.describe()

Age
count   2.000000
mean   31.500000
std     9.192388
min    25.000000
25%    28.250000
50%    31.500000
75%    34.750000
max    38.000000

In [35]:
# quiz : 타이타닉 데이터셋을 찾아서 dataframe으로 읽어오기

In [63]:
url = 'https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv'
df = pd.read_csv(url)
df

Survived  Pclass                                               Name  \
0           0       3                             Mr. Owen Harris Braund   
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2           1       3                              Miss. Laina Heikkinen   
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4           0       3                            Mr. William Henry Allen   
..        ...     ...                                                ...   
882         0       2                               Rev. Juozas Montvila   
883         1       1                        Miss. Margaret Edith Graham   
884         0       3                     Miss. Catherine Helen Johnston   
885         1       1                               Mr. Karl Howell Behr   
886         0       3                                 Mr. Patrick Dooley   

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0      male  22.0                        1                        0   7.2500  
1    female  38.0                        1                        0  71.2833  
2    female  26.0                        0                        0   7.9250  
3    female  35.0                        1                        0  53.1000  
4      male  35.0                        0                        0   8.0500  
..      ...   ...                      ...                      ...      ...  
882    male  27.0                        0                        0  13.0000  
883  female  19.0                        0                        0  30.0000  
884  female   7.0                        1                        2  23.4500  
885    male  26.0                        0                        0  30.0000  
886    male  32.0                        0                        0   7.7500  

[887 rows x 8 columns]

In [64]:
df[df['Sex'] == 'female']

Survived  Pclass                                               Name  \
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2           1       3                              Miss. Laina Heikkinen   
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
8           1       3   Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson   
9           1       2                 Mrs. Nicholas (Adele Achem) Nasser   
..        ...     ...                                                ...   
876         1       2        Mrs. William (Imanita Parrish Hall) Shelley   
878         0       3                        Miss. Gerda Ulrika Dahlberg   
881         0       3                Mrs. William (Margaret Norton) Rice   
883         1       1                        Miss. Margaret Edith Graham   
884         0       3                     Miss. Catherine Helen Johnston   

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
1    female  38.0                        1                        0  71.2833  
2    female  26.0                        0                        0   7.9250  
3    female  35.0                        1                        0  53.1000  
8    female  27.0                        0                        2  11.1333  
9    female  14.0                        1                        0  30.0708  
..      ...   ...                      ...                      ...      ...  
876  female  25.0                        0                        1  26.0000  
878  female  22.0                        0                        0  10.5167  
881  female  39.0                        0                        5  29.1250  
883  female  19.0                        0                        0  30.0000  
884  female   7.0                        1                        2  23.4500  

[314 rows x 8 columns]

In [65]:
# 조건에 맞는 행 출력
df[(df['Sex']=='재ㅡ') & (df['Age']>=30.0)]

Empty DataFrame
Columns: [Survived, Pclass, Name, Sex, Age, Siblings/Spouses Aboard, Parents/Children Aboard, Fare]
Index: []

In [66]:
# 속성 값 바꾸기
df['Sex'] = df['Sex'].replace('female', 'Woman')
df['Sex'] = df['Sex'].replace(['male','Woman'], ['man', 'woman'])
df

Survived  Pclass                                               Name  \
0           0       3                             Mr. Owen Harris Braund   
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2           1       3                              Miss. Laina Heikkinen   
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4           0       3                            Mr. William Henry Allen   
..        ...     ...                                                ...   
882         0       2                               Rev. Juozas Montvila   
883         1       1                        Miss. Margaret Edith Graham   
884         0       3                     Miss. Catherine Helen Johnston   
885         1       1                               Mr. Karl Howell Behr   
886         0       3                                 Mr. Patrick Dooley   

       Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0      man  22.0                        1                        0   7.2500  
1    woman  38.0                        1                        0  71.2833  
2    woman  26.0                        0                        0   7.9250  
3    woman  35.0                        1                        0  53.1000  
4      man  35.0                        0                        0   8.0500  
..     ...   ...                      ...                      ...      ...  
882    man  27.0                        0                        0  13.0000  
883  woman  19.0                        0                        0  30.0000  
884  woman   7.0                        1                        2  23.4500  
885    man  26.0                        0                        0  30.0000  
886    man  32.0                        0                        0   7.7500  

[887 rows x 8 columns]

In [67]:
df.isnull().sum()

Survived                   0
Pclass                     0
Name                       0
Sex                        0
Age                        0
Siblings/Spouses Aboard    0
Parents/Children Aboard    0
Fare                       0
dtype: int64

In [69]:
# 열 이름 바꾸기
df.rename(columns={'Pclass':'Passenger Class', 'Sex':'Gender'})

Survived  Passenger Class  \
0           0                3   
1           1                1   
2           1                3   
3           1                1   
4           0                3   
..        ...              ...   
882         0                2   
883         1                1   
884         0                3   
885         1                1   
886         0                3   

                                                  Name Gender   Age  \
0                               Mr. Owen Harris Braund    man  22.0   
1    Mrs. John Bradley (Florence Briggs Thayer) Cum...  woman  38.0   
2                                Miss. Laina Heikkinen  woman  26.0   
3          Mrs. Jacques Heath (Lily May Peel) Futrelle  woman  35.0   
4                              Mr. William Henry Allen    man  35.0   
..                                                 ...    ...   ...   
882                               Rev. Juozas Montvila    man  27.0   
883                        Miss. Margaret Edith Graham  woman  19.0   
884                     Miss. Catherine Helen Johnston  woman   7.0   
885                               Mr. Karl Howell Behr    man  26.0   
886                                 Mr. Patrick Dooley    man  32.0   

     Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0                          1                        0   7.2500  
1                          1                        0  71.2833  
2                          0                        0   7.9250  
3                          1                        0  53.1000  
4                          0                        0   8.0500  
..                       ...                      ...      ...  
882                        0                        0  13.0000  
883                        0                        0  30.0000  
884                        1                        2  23.4500  
885                        0                        0  30.0000  
886                        0                        0   7.7500  

[887 rows x 8 columns]

In [70]:
# 모든 열이름 한번에 바꾸기
import collections

# 빈 딕셔너리 만들기
column_names = collections.defaultdict(str)

# 키값 만들기
for name in df.columns:
    column_names[name]

column_names


defaultdict(str,
            {'Survived': '',
             'Pclass': '',
             'Name': '',
             'Sex': '',
             'Age': '',
             'Siblings/Spouses Aboard': '',
             'Parents/Children Aboard': '',
             'Fare': ''})

In [71]:
print(df['Age'].max())
print(df['Age'].min())
print(df['Age'].mean())
print(df['Age'].sum())
print(df['Age'].count())

80.0
0.42
29.471443066516347
26141.17
887


In [72]:
df.count()

Survived                   887
Pclass                     887
Name                       887
Sex                        887
Age                        887
Siblings/Spouses Aboard    887
Parents/Children Aboard    887
Fare                       887
dtype: int64

In [76]:
df['Sex'].unique()  # 고유값을 뽑아낸다

array(['man', 'woman'], dtype=object)

In [78]:
df['Sex'].value_counts()  # 고유값의 각각의 갯수(숫자)를 뽑는다

man      573
woman    314
Name: Sex, dtype: int64

In [81]:
# 고유값의 갯수(man, woman)
df['Sex'].nunique()

2

In [84]:
df[df['Age'].isnull()].head()

Empty DataFrame
Columns: [Survived, Pclass, Name, Sex, Age, Siblings/Spouses Aboard, Parents/Children Aboard, Fare]
Index: []

In [85]:
df.drop('Age', axis=1).head()

Survived  Pclass                                               Name    Sex  \
0         0       3                             Mr. Owen Harris Braund    man   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...  woman   
2         1       3                              Miss. Laina Heikkinen  woman   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle  woman   
4         0       3                            Mr. William Henry Allen    man   

   Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0                        1                        0   7.2500  
1                        1                        0  71.2833  
2                        0                        0   7.9250  
3                        1                        0  53.1000  
4                        0                        0   8.0500

In [86]:
df.drop(['Age','Sex'], axis=1)  # 열 이름 여러개를 한꺼번에 삭제

Survived  Pclass                                               Name  \
0           0       3                             Mr. Owen Harris Braund   
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2           1       3                              Miss. Laina Heikkinen   
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4           0       3                            Mr. William Henry Allen   
..        ...     ...                                                ...   
882         0       2                               Rev. Juozas Montvila   
883         1       1                        Miss. Margaret Edith Graham   
884         0       3                     Miss. Catherine Helen Johnston   
885         1       1                               Mr. Karl Howell Behr   
886         0       3                                 Mr. Patrick Dooley   

     Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0                          1                        0   7.2500  
1                          1                        0  71.2833  
2                          0                        0   7.9250  
3                          1                        0  53.1000  
4                          0                        0   8.0500  
..                       ...                      ...      ...  
882                        0                        0  13.0000  
883                        0                        0  30.0000  
884                        1                        2  23.4500  
885                        0                        0  30.0000  
886                        0                        0   7.7500  

[887 rows x 6 columns]

In [88]:
df[df['Name'] != 'Mr. Patrick Dooley']

Survived  Pclass                                               Name  \
0           0       3                             Mr. Owen Harris Braund   
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2           1       3                              Miss. Laina Heikkinen   
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4           0       3                            Mr. William Henry Allen   
..        ...     ...                                                ...   
881         0       3                Mrs. William (Margaret Norton) Rice   
882         0       2                               Rev. Juozas Montvila   
883         1       1                        Miss. Margaret Edith Graham   
884         0       3                     Miss. Catherine Helen Johnston   
885         1       1                               Mr. Karl Howell Behr   

       Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0      man  22.0                        1                        0   7.2500  
1    woman  38.0                        1                        0  71.2833  
2    woman  26.0                        0                        0   7.9250  
3    woman  35.0                        1                        0  53.1000  
4      man  35.0                        0                        0   8.0500  
..     ...   ...                      ...                      ...      ...  
881  woman  39.0                        0                        5  29.1250  
882    man  27.0                        0                        0  13.0000  
883  woman  19.0                        0                        0  30.0000  
884  woman   7.0                        1                        2  23.4500  
885    man  26.0                        0                        0  30.0000  

[886 rows x 8 columns]

In [89]:
df[df.index != 0]

Survived  Pclass                                               Name  \
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2           1       3                              Miss. Laina Heikkinen   
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4           0       3                            Mr. William Henry Allen   
5           0       3                                    Mr. James Moran   
..        ...     ...                                                ...   
882         0       2                               Rev. Juozas Montvila   
883         1       1                        Miss. Margaret Edith Graham   
884         0       3                     Miss. Catherine Helen Johnston   
885         1       1                               Mr. Karl Howell Behr   
886         0       3                                 Mr. Patrick Dooley   

       Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
1    woman  38.0                        1                        0  71.2833  
2    woman  26.0                        0                        0   7.9250  
3    woman  35.0                        1                        0  53.1000  
4      man  35.0                        0                        0   8.0500  
5      man  27.0                        0                        0   8.4583  
..     ...   ...                      ...                      ...      ...  
882    man  27.0                        0                        0  13.0000  
883  woman  19.0                        0                        0  30.0000  
884  woman   7.0                        1                        2  23.4500  
885    man  26.0                        0                        0  30.0000  
886    man  32.0                        0                        0   7.7500  

[886 rows x 8 columns]

In [90]:
df.drop_duplicates()

Survived  Pclass                                               Name  \
0           0       3                             Mr. Owen Harris Braund   
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2           1       3                              Miss. Laina Heikkinen   
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4           0       3                            Mr. William Henry Allen   
..        ...     ...                                                ...   
882         0       2                               Rev. Juozas Montvila   
883         1       1                        Miss. Margaret Edith Graham   
884         0       3                     Miss. Catherine Helen Johnston   
885         1       1                               Mr. Karl Howell Behr   
886         0       3                                 Mr. Patrick Dooley   

       Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0      man  22.0                        1                        0   7.2500  
1    woman  38.0                        1                        0  71.2833  
2    woman  26.0                        0                        0   7.9250  
3    woman  35.0                        1                        0  53.1000  
4      man  35.0                        0                        0   8.0500  
..     ...   ...                      ...                      ...      ...  
882    man  27.0                        0                        0  13.0000  
883  woman  19.0                        0                        0  30.0000  
884  woman   7.0                        1                        2  23.4500  
885    man  26.0                        0                        0  30.0000  
886    man  32.0                        0                        0   7.7500  

[887 rows x 8 columns]

In [91]:
print('Number of Rows in the original Dataframe', len(df))

Number of Rows in the original Dataframe 887


In [93]:
print(len(df.drop_duplicates()))

887


In [94]:
df.drop_duplicates(subset=['Sex'])

Survived  Pclass                                               Name    Sex  \
0         0       3                             Mr. Owen Harris Braund    man   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...  woman   

    Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0  22.0                        1                        0   7.2500  
1  38.0                        1                        0  71.2833

In [95]:
df.drop_duplicates(subset=['Sex'], keep='last')

Survived  Pclass                            Name    Sex   Age  \
884         0       3  Miss. Catherine Helen Johnston  woman   7.0   
886         0       3              Mr. Patrick Dooley    man  32.0   

     Siblings/Spouses Aboard  Parents/Children Aboard   Fare  
884                        1                        2  23.45  
886                        0                        0   7.75

In [98]:
# quiz : pclass에서 중복된 값 제거
df.drop_duplicates(subset=['Pclass'])

Survived  Pclass                                               Name    Sex  \
0         0       3                             Mr. Owen Harris Braund    man   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...  woman   
9         1       2                 Mrs. Nicholas (Adele Achem) Nasser  woman   

    Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0  22.0                        1                        0   7.2500  
1  38.0                        1                        0  71.2833  
9  14.0                        1                        0  30.0708

In [101]:
df.groupby('Sex').mean()  # 묶어서 평균을 계산

Survived    Pclass        Age  Siblings/Spouses Aboard  \
Sex                                                             
man    0.190227  2.385689  30.431361                 0.432810   
woman  0.742038  2.159236  27.719745                 0.694268   

       Parents/Children Aboard       Fare  
Sex                                        
man                   0.237347  25.633935  
woman                 0.649682  44.479818

In [102]:
df.groupby('Survived')['Name'].count()

Survived
0    545
1    342
Name: Name, dtype: int64

In [103]:
df.groupby(['Sex', 'Survived'])['Age'].count()

Sex    Survived
man    0           464
       1           109
woman  0            81
       1           233
Name: Age, dtype: int64

In [110]:
# resample을 사용해서 시간 간격에 따라 행 그룹핑

import pandas as pd
import numpy as np

time_index = pd.date_range('06/06/2017', periods=100000, freq='30S')

dataframe = pd.DataFrame(index=time_index)

dataframe['Sale_Amount'] = np.random.randint(1,10,100000)
dataframe

Sale_Amount
2017-06-06 00:00:00            2
2017-06-06 00:00:30            1
2017-06-06 00:01:00            9
2017-06-06 00:01:30            4
2017-06-06 00:02:00            9
...                          ...
2017-07-10 17:17:30            6
2017-07-10 17:18:00            2
2017-07-10 17:18:30            3
2017-07-10 17:19:00            3
2017-07-10 17:19:30            7

[100000 rows x 1 columns]

In [111]:
dataframe.resample('W').sum() # 'W' 는 1주일 단위로 그룹핑 후 평균 계산

Sale_Amount
2017-06-11        86054
2017-06-18       100800
2017-06-25       101411
2017-07-02       100516
2017-07-09       100410
2017-07-16        10233

In [112]:
dataframe.resample('2W').mean() # '2W' 는 2주일 단위로 그룹핑 후 평균 계산

Sale_Amount
2017-06-11     4.979977
2017-06-25     5.015154
2017-07-09     4.983284
2017-07-23     4.919712

In [113]:
dataframe.resample('1M').mean()  # 1달 단위로 그룹핑 후 평균계산

Sale_Amount
2017-06-30     5.002514
2017-07-31     4.972964

In [125]:
# 최대-최소 변환과정으로 정규화

import numpy as np
from sklearn import preprocessing

feature = np.array([[-500.5],
                    [-100.1],
                    [0],
                    [100.1],
                    [900.9]])

minmax_scale = preprocessing.MinMaxScaler(feature_range=(0,1))

scaled_feature = minmax_scale.fit_transform(feature)

scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [126]:
x = np.array([[-1000.5],
              [-200.2],
              [500.5],
              [600.6],
              [9000.9]])

In [127]:
# 정규화 - 데이터들의 평균 0, 표준편차 1로 변환

scaler = preprocessing.StandardScaler()

standardized = scaler.fit_transform(x)

standardized

array([[-0.76065756],
       [-0.54174106],
       [-0.35006945],
       [-0.32268779],
       [ 1.97515586]])

In [129]:
print(round(standardized.mean()))
print(standardized.std())

0
1.0


In [130]:
# 결측치가 많을 경우 중간값, 사분위값 등으로 대체하는 RobustScaler

robust_scaler = preprocessing.RobustScaler()
robust_scaler.fit_transform(x)

array([[-1.87437562],
       [-0.875     ],
       [ 0.        ],
       [ 0.125     ],
       [10.61488511]])

In [133]:
import numpy as np
from sklearn.covariance import EllipticEnvelope
from sklearn.datasets import make_blobs

features, _ = make_blobs(n_samples = 10,
                        n_features = 2,
                        centers = 1,
                        random_state= 1)

features[0,0] = 10000
features[1,0] = 10000

outlier_detector = EllipticEnvelope(contamination=.1)

outlier_detector.fit(features)
outlier_detector.predict(features)

array([ 1, -1,  1,  1,  1,  1,  1,  1,  1,  1])